### PR TITLE
IDEM-38

### PR DESCRIPTION
**Pull request by amagon270**
Story: Added message when no valid documents for verification are available
image

### CODE REVIEW

**Review by jrocca82 — DISMISSED** [review]

**Comment by bitcoinbrisbane** [comment]
Looks ok.  Let me pull down the branch and see in a sim

**Comment by amagon270** [comment]
> Should be a list of documents to select

There is.  
image

All acceptance criteria of this ticket except for
* If no documents are available I am prompted to add the required documents
are already in the main branch so this PR is just adding the final acceptance criteria

**Comment by bitcoinbrisbane** [comment]
> > Should be a list of documents to select
> 
> There is. image
> 
> All acceptance criteria of this ticket except for
> 
> * If no documents are available I am prompted to add the required documents
> 
> are already in the main branch so this PR is just adding the final acceptance criteria

Ok got ya.  Maybe do an alert instead to keep with the them?

**Comment by amagon270** [comment]
Alert box prompt
image

**Comment by amagon270** [comment]
updated description photo to show new alert box

**Review by jrocca82 — APPROVED** [review]

**Pull request merged**
