### PR TITLE
Eject

### PR DESCRIPTION
**Pull request by amagon270**
Don't merge this until everyone knows how to set up the project post-eject

### CODE REVIEW

**Review by bitcoinbrisbane — DISMISSED** [review]

**Comment by xcjlo985** [comment]
@amagon270 have you reviewed the sonar issues? Looks like they're security related

**Comment by bitcoinbrisbane** [comment]
> @amagon270 have you reviewed the sonar issues? Looks like they're security related

Yes, we can remove a few of the device permissions.  

* Record audio
* 

image

**Review by xiangzhe0812 — APPROVED** [review]

**Review by bitcoinbrisbane — CHANGES_REQUESTED** [review]
LGTM

**Review by bitcoinbrisbane — APPROVED** [review]
LGTM

**Pull request merged**
