### PR TITLE
IDEM-247

### PR DESCRIPTION
**Pull request by pondpiu**
#247 

- add digital surge to vendor list

will need to update proxy to know about digital surge signup endpoint as well

Screen Shot 2022-07-19 at 10 06 32 am

### CODE REVIEW

**Review by bitcoinbrisbane — CHANGES_REQUESTED** [review]
Need to roll back useProxy flag

**Comment by bitcoinbrisbane** [comment]
@pondpiu also see if you can make a background colour

**Review by bitcoinbrisbane — APPROVED** [review]

**Review by bitcoinbrisbane — CHANGES_REQUESTED** [review]
Remove the white space around the logo

**Review by xiangzhe0812 — APPROVED** [review]

**Review by JasminFarhi — APPROVED** [review]

**Comment by bitcoinbrisbane** [comment]
@JasminFarhi to fix the logo

**Comment by JasminFarhi** [comment]
> Remove the white space around the logo

I have added a new logo :)

**Comment by bitcoinbrisbane** [comment]
@JasminFarhi need to merge main in first as you've rolled back @bazmatic images

**Review by bitcoinbrisbane — CHANGES_REQUESTED** [review]
Don't include the images in the pr

**Review by bitcoinbrisbane — DISMISSED** [review]

**Review by bitcoinbrisbane — APPROVED** [review]

**Review by xiangzhe0812 — APPROVED** [review]

**Pull request merged**
